[[redirects]]
  # Requests to URLs matching this pattern...
  # from = "/images/uploads/:file"
  # ...will resolve to this URL pattern
  # to = "/.netlify/images/uploads/?url=/images/:file"
  # ... and the status code of 200 will make this behave as a rewrite
  # status = 200
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200