backend: # The two following lines need to be indented
  name: git-gateway # The authentication method we use for Netlify CMS
  branch: main # Branch to update when we push our content (it can be any branch in our repo)

# Do not indent these lines
media_folder: "public/images/uploads" # Exact path where we store the uploaded media
public_folder: "/images/uploads" # We do not need to specify the /public part as all the files from it are stored in the root directory after the build step

site_url: https://prince-collection.netlify.app/ # Replace with site's URL
display_url: https://prince-collection.netlify.app/ # Replace with site's URL

logo_url: /images/logo-crown.png # Replace with path to logo

slug: { { slug } } # The URL should be the name of the title of the post/document

collections:
  - label: blog # Label used in the UI for the collection
    label_singular: post # Label for singular post
    name: blog # Name of the collection used for various functionality in the CMS
    folder: /src/content/blog # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Title", name: "title", widget: "string" } # Field Title
      - { label: "Author", name: "author", widget: "string" } # Field Title
      - { label: "Description", name: "description", widget: "string" } # Field Description
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }
      - { label: "Featured image", name: "imageUrl", widget: "image" } # Field Featured Image
      - { label: "Image Alt text", name: "imageAlt", widget: "string" } # 
      - { label: "Tags", name: "tags", widget: "list", default: ["blog"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }




  - label: guides # Label used in the UI for the collection
    label_singular: guide # Label for singular post
    name: guides # Name of the collection used for various functionality in the CMS
    folder: /src/content/guides # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Title", name: "title", widget: "string" } # Field Title
      - { label: "Author", name: "author", widget: "string" } # Field Title
      - { label: "Description", name: "description", widget: "string" } # Field Description
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Featured image", name: "imageUrl", widget: "image" } # Field Featured Image
      - { label: "Image Alt text", name: "imageAlt", widget: "string" } 
      - { label: "Tags", name: "tags", widget: "list", default: ["guides"] }
      - {label: "Body", name: "body", widget: "markdown"}
  - label: news # Label used in the UI for the collection
    label_singular: post # Label for singular post
    name: news # Name of the collection used for various functionality in the CMS
    folder: /src/content/news # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Title", name: "title", widget: "string" } # Field Title
      - { label: "Author", name: "author", widget: "string" } # Field Title
      - { label: "Description", name: "description", widget: "string" } # Field Description
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Featured image", name: "imageUrl", widget: "image" } # Field Featured Image
      - { label: "Image Alt text", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] } 
      - {label: "Body", name: "body", widget: "markdown"}
  - label: reviews # Label used in the UI for the collection
    label_singular: post # Label for singular post
    name: reviews # Name of the collection used for various functionality in the CMS
    folder: /src/content/reviews # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Title", name: "title", widget: "string" } # Field Title
      - { label: "Author", name: "author", widget: "string" } # Field Title
      - { label: "Description", name: "description", widget: "string" } # Field Description
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Featured image", name: "imageUrl", widget: "image" } # Field Featured Image
      - { label: "Image Alt text", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["reviews"] } 
      - {label: "Body", name: "body", widget: "markdown"}

# use fields for credit card or other ads, then use v-if on a component inside the MD

