backend: # The two following lines need to be indented
  name: git-gateway # The authentication method we use for Netlify CMS
  branch: main # Branch to update when we push our content (it can be any branch in our repo)

# Do not indent these lines
media_folder: "public/images/uploads" # Exact path where we store the uploaded media
public_folder: "/images/uploads" # We do not need to specify the /public part as all the files from it are stored in the root directory after the build step

site_url: https://prince-collection.netlify.app/ # Replace with site's URL
display_url: https://prince-collection.netlify.app/ # Replace with site's URL

logo_url: /img/logos/logo-crown.png # Replace with path to logo

slug: { { slug } } # The URL should be the name of the title of the post/document

collections:
  - label: blog # Label used in the UI for the collection
    label_singular: post # Label for singular post
    name: blog # Name of the collection used for various functionality in the CMS
    folder: /src/pages/blog # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Title", name: "title", widget: "string" } # Field Title
      - { label: "Author", name: "author", widget: "string" } # Field Title
      - { label: "Description", name: "description", widget: "markdown" } # Field Description
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Featured image", name: "imageUrl", widget: "image" } # Field Featured Image
      - { label: "Image Alt text", name: "imageAlt", widget: "string" } # 
      - {label: "Body", name: "body", widget: "json"}
  - label: guides # Label used in the UI for the collection
    label_singular: guide # Label for singular post
    name: guides # Name of the collection used for various functionality in the CMS
    folder: /src/pages/guides # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Title", name: "title", widget: "string" } # Field Title
      - { label: "Author", name: "author", widget: "string" } # Field Title
      - { label: "Description", name: "description", widget: "markdown" } # Field Description
      - { label: "Date of writing", name: "date", widget: "DateTime" } # Field Date of writing
      - { label: "Featured image", name: "featuredImage", widget: "image" } # Field Featured Image
      - {label: "Body", name: "body", widget: "markdown"}
  - label: news # Label used in the UI for the collection
    label_singular: post # Label for singular post
    name: news # Name of the collection used for various functionality in the CMS
    folder: /src/pages/news # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Title", name: "title", widget: "string" } # Field Title
      - { label: "Author", name: "author", widget: "string" } # Field Title
      - { label: "Description", name: "description", widget: "markdown" } # Field Description
      - { label: "Date of writing", name: "date", widget: "DateTime" } # Field Date of writing
      - { label: "Featured image", name: "featuredImage", widget: "image" } # Field Featured Image
      - {label: "Body", name: "body", widget: "markdown"}

# use fields for credit card or other ads, then use v-if on a component inside the MD

